<?php

class Correios_Sigep_Acao
{
    const __default = 'DEVOLVIDO_AO_REMETENTE';
    const DEVOLVIDO_AO_REMETENTE = 'DEVOLVIDO_AO_REMETENTE';
    const ENCAMINHADO_PARA_REFUGO = 'ENCAMINHADO_PARA_REFUGO';
    const REINTEGRADO_E_DEVOLVIDO_AO_REMETENTE = 'REINTEGRADO_E_DEVOLVIDO_AO_REMETENTE';
    const DESBLOQUEADO = 'DESBLOQUEADO';


}
