<?php

class Correios_Sigep_TipoBloqueio
{
    const __default = 'FRAUDE_BLOQUEIO';
    const FRAUDE_BLOQUEIO = 'FRAUDE_BLOQUEIO';
    const EXTRAVIO_VAREJO_PRE_INDENIZADO = 'EXTRAVIO_VAREJO_PRE_INDENIZADO';
    const EXTRAVIO_VAREJO_POS_INDENIZADO = 'EXTRAVIO_VAREJO_POS_INDENIZADO';
    const EXTRAVIO_CORPORATIVO = 'EXTRAVIO_CORPORATIVO';
    const INTERNACIONAL_LDI = 'INTERNACIONAL_LDI';


}
